/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        grove: {
          50: 'var(--color-grove-50)',
          100: 'var(--color-grove-100)',
          200: 'var(--color-grove-200)',
          300: 'var(--color-grove-300)',
          400: 'var(--color-grove-400)',
          500: 'var(--color-grove-500)',
          600: 'var(--color-grove-600)',
          700: 'var(--color-grove-700)',
          800: 'var(--color-grove-800)',
          900: 'var(--color-grove-900)',
        },
      },
      fontFamily: {
        header: ['var(--font-header)'],
        copy: ['var(--font-copy)'],
      },
      fontSize: {
        md: '1rem',
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        38: '9.5rem',
        40: '10rem',
        42: '10.5rem',
        44: '11rem',
        48: '12rem',
        50: '12.5rem',
        54: '13.5rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        66: '16.5rem',
        76: '19rem',
        80: '20rem',
        88: '22rem',
        100: '25rem',
        110: '27.5rem',
        112: '28rem',
        120: '30rem',
        128: '32rem',
        144: '36rem',
        150: '37.5rem',
        156: '39rem',
        172: '43rem',
        192: '48rem',
        196: '49rem',
        200: '50rem',
        212: '53rem',
        232: '58rem',
        250: '62.5rem',
        272: '68rem',
        300: '75rem',
      },
      inset: {
        '5/16': '31.25%',
        '5/32': '15.625%',
      },
      maxWidth: {
        196: '49rem',
        212: '53rem',
      },
      width: {
        xs: '20rem',
        xl: '36rem',
        '2xl': '42rem',
        '4xl': '56rem',
      },
      minHeight: {
        110: '27.5rem',
        144: '36rem',
        172: '43rem',
        232: '58rem',
        250: '62.5rem',
        300: '75rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      borderWidth: {
        6: '6px',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'slide-in-bottom': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        surfer: {
          '0%': { transform: 'translateX(-300%) translateY(-25%) scale(0.8)', opacity: '0' },
          '100%': { transform: 'translateX(0) translateY(0) scale(1)', opacity: '1' },
        },
        wave: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2vw)' },
        },
        boat: {
          '0%': { transform: 'translateX(-100%) scale(0.5)', opacity: '0' },
          '100%': { transform: 'translateX(0) scale(1)', opacity: '1' },
        },
        'boat-wave': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8%)' },
        },
        dolphin: {
          '0%': { offsetDistance: '0%', rotate: '-30deg', opacity: '0' },
          '100%': { offsetDistance: '100%', rotate: '0deg', opacity: '1' },
        },
        jellyfish: {
          '0%': { transform: 'translate(50px, 300px)', rotate: '-10deg', opacity: '0' },
          '100%': { transform: 'translate(0, 0)', rotate: '0deg', opacity: '1' },
        },
        fish: {
          '0%': { transform: 'translateX(-200%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        sun: 'fade-in 0.8s ease-out forwards',
        'slide-in-bottom': 'slide-in-bottom 0.8s ease-out forwards',
        'slide-in-left': 'slide-in-left 1.6s ease-out forwards',
        surfer: 'surfer 2.4s ease-out forwards, boat-wave 3.2s ease-in-out infinite 3.4s',
        rocket: 'slide-in-bottom 2.4s ease-out forwards',
        wave: 'wave 3.2s ease-in-out 0.3s infinite',
        'ocean-top': 'wave 3.2s ease-in-out infinite',
        'ocean-left': 'wave 3.2s ease-in-out infinite',
        'ocean-right': 'wave 3.2s ease-in-out infinite',
        boat: 'boat 3.4s ease-out forwards, boat-wave 3.2s ease-in-out infinite 3.4s',
        'smoke-1': 'fade-in 0.8s ease-out forwards',
        'smoke-2': 'fade-in 0.8s ease-out forwards',
        'smoke-3': 'fade-in 0.8s ease-out forwards 0.4s',
        'smoke-4': 'fade-in 0.8s ease-out forwards 0.8s',
        'smoke-5': 'fade-in 0.8s ease-out forwards 1.2s',
        'smoke-6': 'fade-in 0.8s ease-out forwards 1.2s',
        'smoke-7': 'fade-in 0.8s ease-out forwards 1.6s',
        'smoke-8': 'fade-in 0.8s ease-out forwards 2s',
        dolphin: 'dolphin 2s ease-in-out forwards, boat-wave 3.2s ease-in-out infinite 2s',
        jellyfish: 'jellyfish 3s ease-in-out forwards, boat-wave 6.4s ease-in-out infinite 3s',
        'jellyfish-big': 'jellyfish 3s ease-in-out forwards, boat-wave 6.4s ease-in-out infinite 3s',
        fish: 'fish 1.6s ease-out forwards, boat-wave 3.2s ease-in-out infinite 1.6s',
        'sun-rays': 'fade-in 0.8s ease-out forwards',
      },
    },
  },
  plugins: [],
};